### ISSUE TITLE
Accept duration parameter in TeamCity-TestFinished

### ISSUE THREAD

**Issue by mwrock** [psake/psake-contrib#6]
According to [TeamCity's documentation] (http://confluence.jetbrains.net/display/TCD65/Build+Script+Interaction+with+TeamCity), the testFinished service message can take a duration attribute that specifies the amount of time a test has taken:

    ##teamcity[testFinished name='testname' duration='<test_duration_in_milliseconds>']

The current teamcity.psm1 only accepts the name attribute. While that certainly satisfies most cases and will cause TeamCity to measure the time by the span between the testStarted and testFinished messages, I recently had a need for this where I spawned concurrent jobs to hit http endpoints and then come back with results. Each job tracked the time taken within its own thread.

I modified the function to optionally take a duration parameter. Pull request coming...

**Comment by gep13** [comment]
Looks like this issue was closed, via the merged Pull Request, so going to close it.

Thanks!
