### ISSUE TITLE
Publish psake-contrib nuget package

### ISSUE THREAD

**Issue by jrnail23** [psake/psake-contrib#8]
I noticed that a nuspec has been added to the project, but it doesn't look like a psake-contrib package is actually available on nuget.org.

**Comment by youngcm2** [comment]
bump

**Comment by gep13** [comment]
Looks like this package already exists:

https://www.nuget.org/packages/psake-contrib

I have asked the current maintainer to add me as a maintainer, so that I can push a new version with the PR's that I have just merged in.  Thanks!

**Comment by gep13** [comment]
I now have ownership of this nuget package, so any new updates to this repository will be pushed as an update to the nuget package.

**Comment by gep13** [comment]
The latest version of psake-contrib has now been pushed to Nuget: https://www.nuget.org/packages/psake-contrib/
